pet-sitting/config/routes.rb
Rails.application.routes.draw do
  resources :sitters

end

pet-sitting/app/models/sitter.rb
class Sitter < ActiveRecord::Base
end

pet-sitting/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

pet-sitting/app/controllers/sitters_controller.rb
class SittersController < ApplicationController
  before_action :set_sitter, only: [:show, :edit, :update, :destroy]

  # GET /sitters
  # GET /sitters.json
  def index
    @sitters = Sitter.all
  end

  # GET /sitters/1
  # GET /sitters/1.json
  def show
  end

  # GET /sitters/new
  def new
    @sitter = Sitter.new
  end

  # GET /sitters/1/edit
  def edit
  end

  # POST /sitters
  # POST /sitters.json
  def create
    @sitter = Sitter.new(sitter_params)

    respond_to do |format|
      if @sitter.save
        format.html { redirect_to @sitter, notice: 'Sitter was successfully created.' }
        format.json { render :show, status: :created, location: @sitter }
      else
        format.html { render :new }
        format.json { render json: @sitter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sitters/1
  # PATCH/PUT /sitters/1.json
  def update
    respond_to do |format|
      if @sitter.update(sitter_params)
        format.html { redirect_to @sitter, notice: 'Sitter was successfully updated.' }
        format.json { render :show, status: :ok, location: @sitter }
      else
        format.html { render :edit }
        format.json { render json: @sitter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sitters/1
  # DELETE /sitters/1.json
  def destroy
    @sitter.destroy
    respond_to do |format|
      format.html { redirect_to sitters_url, notice: 'Sitter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sitter
      @sitter = Sitter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sitter_params
      params.require(:sitter).permit(:email, :name)
    end
end

pet-sitting/app/helpers/sitters_helper.rb
module SittersHelper
end

pet-sitting/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PetSitting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

pet-sitting/app/views/sitters/_form.html.erb
<%= form_for(@sitter) do |f| %>
  <% if @sitter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sitter.errors.count, "error") %> prohibited this sitter from being saved:</h2>

      <ul>
      <% @sitter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

pet-sitting/app/views/sitters/edit.html.erb
<h1>Editing Sitter</h1>

<%= render 'form' %>

<%= link_to 'Show', @sitter %> |
<%= link_to 'Back', sitters_path %>

pet-sitting/app/views/sitters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sitters</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sitters.each do |sitter| %>
      <tr>
        <td><%= sitter.email %></td>
        <td><%= sitter.name %></td>
        <td><%= link_to 'Show', sitter %></td>
        <td><%= link_to 'Edit', edit_sitter_path(sitter) %></td>
        <td><%= link_to 'Destroy', sitter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sitter', new_sitter_path %>

pet-sitting/app/views/sitters/new.html.erb
<h1>New Sitter</h1>

<%= render 'form' %>

<%= link_to 'Back', sitters_path %>

pet-sitting/app/views/sitters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @sitter.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @sitter.name %>
</p>

<%= link_to 'Edit', edit_sitter_path(@sitter) %> |
<%= link_to 'Back', sitters_path %>